name: quotations
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  data_class_plugin: ^0.2.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
 
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/work_sans/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/work_sans/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/work_sans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/work_sans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/work_sans/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/work_sans/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/work_sans/WorkSans-Black.ttf
          weight: 900
